### PR TITLE
[qutP24Og] add layout, SaleBanner, Header, Footer

### PR DESCRIPTION
**Pull request by trdbau**
# What's this PR/MR do?
1. UI:

2. Function:

3. Impact range:

# Task link
- Example link

# TODO Checkboxes
- [ ] Did you check UI is as same as Figma Design?
- [ ] Did you check Spec/Flow?
- [ ] Did you note influence scope + pull request link in sub task?
- [ ] Did you check all test cases?
  1. Test case 1
  2. Test case 2

# Screenshot (UI task)
| Description | Image |
| --- | --- |
| description_for_img | After |

### CODE REVIEW

**Comment by trdbau** [comment]
[Merge tailwind config ts-js](https://trello.com/c/cfx1kSrJ/9-merge-tailwind-config-ts-js)

**Comment by trdbau** [comment]
[Layout Webapp](https://trello.com/c/qutP24Og/10-layout-webapp)

**Comment by trdbau** [comment]
[Thêm storybook để quản lý component fe](https://trello.com/c/C2qcnKVI/4-th%C3%AAm-storybook-%C4%91%E1%BB%83-qu%E1%BA%A3n-l%C3%BD-component-fe)

**Review by Vantan22 — APPROVED** [review]
LGTM!!

**Review by Vantan22 — APPROVED** [review]

**Review by Vantan22 — APPROVED** [review]

**Pull request merged**
